#!/bin/bash

# Quick Fix Script for Sign-up Issues
# Run: bash fix-signup.sh

echo "🔧 SIGN-UP ISSUE FIX GUIDE"
echo "=========================="
echo ""
echo "CRITICAL ISSUE: HYGRAPH_TOKEN not set in .env"
echo ""
echo "📋 CHECKLIST:"
echo ""
echo "1️⃣  GET HYGRAPH TOKEN:"
echo "   - Go to https://hygraph.com"
echo "   - Login to your account"
echo "   - Select your project"
echo "   - Settings → API Access → Permanent Auth Tokens"
echo "   - Create or copy existing token"
echo "   - Copy the token value"
echo ""
echo "2️⃣  ADD TO .env FILE:"
echo "   - Open D:\shop-backend\brighthex-dream-24-7-backend\.env"
echo "   - Find line with: # HYGRAPH_TOKEN=your_hygraph_mutation_token_here"
echo "   - Replace with: HYGRAPH_TOKEN=your_token_here"
echo "   - Save file"
echo ""
echo "3️⃣  VERIFY MSG91 CREDENTIALS:"
echo "   - Go to https://control.msg91.com"
echo "   - Dashboard → Settings → API Key (should be MSG91_AUTH_KEY)"
echo "   - Templates → Find your template ID (should be MSG91_TEMPLATE_ID)"
echo "   - Verify current values in .env match"
echo ""
echo "4️⃣  RESTART SERVER:"
echo "   - Stop running server (Ctrl+C)"
echo "   - Run: npm start"
echo ""
echo "5️⃣  TEST SIGN-UP:"
echo "   - Frontend: Try signing up with valid mobile"
echo "   - Terminal: Watch server logs for errors"
echo "   - Look for: ✅ or ❌ messages with details"
echo ""
echo "6️⃣  IF STILL FAILING:"
echo "   - Check server logs for error messages"
echo "   - Go to DEVELOPER_SCAN_REPORT.md for detailed troubleshooting"
echo ""
